# http://travis-ci.org/#!/graphite-project/carbon
language: python
python: 2.7
sudo: false

matrix:
  include:
    - python: pypy
      env:
        - TOXENV=pypy
    - python: 3.4
      env:
        - TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.6
      env:
        - TOXENV=lint

env:
  - TOXENV=py27
  - TOXENV=lint

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov
